version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mycontainer
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: projectsdb
